DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS DEVICE;
DROP TABLE IF EXISTS USER_DEVICE;
DROP TABLE IF EXISTS DEVICE_CONSUMPTION;

CREATE TABLE USERS (
USER_ID VARCHAR PRIMARY KEY,
NAME VARCHAR,
ROLE INT
);

CREATE TABLE ADDRESS (
ADDRESS_ID VARCHAR PRIMARY KEY,
STREET VARCHAR,
CITY VARCHAR,
COUNTRY VARCHAR,
POSTAL_CODE VARCHAR
);

CREATE TABLE DEVICE (
DEVICE_ID VARCHAR PRIMARY KEY,
DESCRIPTION VARCHAR,
ADDRESS_ID VARCHAR,
MAXIMUM_HOURLY_ENERGY_CONSUMPTION DOUBLE PRECISION
);

CREATE TABLE USER_DEVICE (
DEVICE_ID VARCHAR,
USER_ID VARCHAR,
PRIMARY KEY (DEVICE_ID,USER_ID)
);

CREATE TABLE DEVICE_CONSUMPTION (
DEVICE_CONSUMPTION_ID VARCHAR PRIMARY KEY,
DEVICE_ID VARCHAR,
TIMESTAMP VARCHAR,
ENERGY DOUBLE PRECISION
);

ALTER TABLE DEVICE ADD CONSTRAINT DEVICE_ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID) ON DELETE CASCADE;
ALTER TABLE USER_DEVICE ADD CONSTRAINT DEVICE_USER_DEVICE_FK FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE (DEVICE_ID) ON DELETE CASCADE;
ALTER TABLE USER_DEVICE ADD CONSTRAINT USER_USER_DEVICE_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE;
ALTER TABLE DEVICE_CONSUMPTION ADD CONSTRAINT DEVICE_DEVICE_CONSUMPTION_FK FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE (DEVICE_ID) ON DELETE CASCADE;